# Generated by Django 5.1.4 on 2025-04-16 18:32

import django.db.models.deletion
import file_requests.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('done', 'Done')], default='waiting', max_length=10)),
                ('time_begin', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(storage=file_requests.storage_backends.ResultStorage(), upload_to='')),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=file_requests.storage_backends.EditedStorage(), upload_to='')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_requests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('done', 'Done')], default='waiting', max_length=10)),
                ('uploaded_name', models.CharField(max_length=100)),
                ('file', models.FileField(storage=file_requests.storage_backends.UploadedStorage(), upload_to='')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_requests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
