# Generated by Django 5.1.4 on 2025-12-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='danger_timings',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
